// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency_injection

import (
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/google/wire"
	"github.com/reangeline/micro_saas/internal/domain/contract/repository"
	usecase6 "github.com/reangeline/micro_saas/internal/domain/contract/usecase/ai"
	usecase4 "github.com/reangeline/micro_saas/internal/domain/contract/usecase/user"
	usecase5 "github.com/reangeline/micro_saas/internal/domain/contract/usecase/wp"
	usecase2 "github.com/reangeline/micro_saas/internal/domain/usecase/ai"
	"github.com/reangeline/micro_saas/internal/domain/usecase/user"
	usecase3 "github.com/reangeline/micro_saas/internal/domain/usecase/wp"
	"github.com/reangeline/micro_saas/internal/infra/database/repository"
	"github.com/reangeline/micro_saas/internal/presentation/controller"
)

// Injectors from wire.go:

func InitializeUser(vc *dynamodb.DynamoDB) (*controller.UserController, error) {
	userRepository := database.NewUserRepository(vc)
	createUserUseCase := usecase.NewCreateUserUseCase(userRepository)
	userController := controller.NewUserController(createUserUseCase)
	return userController, nil
}

func InitializeCreateMessageWhatsApp() (*controller.WhatsAppController, error) {
	createMessageAIUseCase := usecase2.NewCreateMessageAIUseCase()
	createMessageWhatsAppUseCase := usecase3.NewCreateMessageWhatsAppUseCase(createMessageAIUseCase)
	whatsAppController := controller.NewWhatsAppController(createMessageWhatsAppUseCase)
	return whatsAppController, nil
}

// wire.go:

var setCreateUserUseCaseDependency = wire.NewSet(usecase.NewCreateUserUseCase, wire.Bind(new(usecase4.CreateUserUseCaseInterface), new(*usecase.CreateUserUseCase)))

var setUserRepositoryDependency = wire.NewSet(database.NewUserRepository, wire.Bind(new(contract.UserRepositoryInterface), new(*database.UserRepository)))

var setCreateMessageWhatsAppUseCaseDependency = wire.NewSet(usecase3.NewCreateMessageWhatsAppUseCase, wire.Bind(new(usecase5.CreateMessageWhatsAppUseCaseInterface), new(*usecase3.CreateMessageWhatsAppUseCase)))

var setCreateMessageAIUseCaseDependency = wire.NewSet(usecase2.NewCreateMessageAIUseCase, wire.Bind(new(usecase6.CreateMessageAIUseCaseInterface), new(*usecase2.CreateMessageAIUseCase)))
